// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE6LUSgGQjjiwWq8NNzhxy03zvyDYrsRs',
    appId: '1:32831083920:android:5aad490d691262805a0f15',
    messagingSenderId: '32831083920',
    projectId: 'voice-app-bdbc8',
    storageBucket: 'voice-app-bdbc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmZ75T3tt25OLmyUv5ymijNw9JW1Wnrg',
    appId: '1:32831083920:ios:ed84cdd047ee87e25a0f15',
    messagingSenderId: '32831083920',
    projectId: 'voice-app-bdbc8',
    storageBucket: 'voice-app-bdbc8.firebasestorage.app',
    iosBundleId: 'com.example.voiceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dIbQedCo3vwwPaNyU0iJFlIymNByErI',
    appId: '1:32831083920:web:111a8c8d8add35eb5a0f15',
    messagingSenderId: '32831083920',
    projectId: 'voice-app-bdbc8',
    authDomain: 'voice-app-bdbc8.firebaseapp.com',
    storageBucket: 'voice-app-bdbc8.firebasestorage.app',
    measurementId: 'G-ZQDYNLTVNZ',
  );

}